### ISSUE TITLE
Error is displayed when @NonNull fields are set in a different method before invoking build() method

### ISSUE THREAD

**Issue by raghusam** [dorukguner/lombok-builder-helper#7]
This plugin is not considering if `@NonNull` attributes are set using builder in a different method.  An example code which is shown as error is as follows : 

Sample class:
``` java
@Value
@Builder
public class Price {
    @NonNull
    private String value;
    @NonNull
    private String currencyUnit;
}
```

``` java
public static Price getPrice() {
   //Following line is being shown as an error even when all the attributes are set in the method invoked to get builder object. 
    getPriceBuilder().build(); 
}

public static Price.PriceBuilder getPriceBuilder() {
        return Price.builder().currencyUnit("USD").value("10.0");
}

```

Error message on IDE is as follows : 
<img width="779" alt="Screenshot 2023-01-31 at 7 57 22 PM" src="https://user-images.githubusercontent.com/13663800/215787465-aefab804-92a0-4988-870b-4b37ef710798.png">

**Comment by dorukguner** [comment]
Thanks for the bug report, this is now fixed in the v1.4.0 release and should be available in the jetbrains marketplace within 2 business days.
